# Generated by Django 3.2.6 on 2021-12-30 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='text_added',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_added',
        ),
        migrations.AddField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
