# Generated by Django 3.2.6 on 2022-01-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0003_auto_20211230_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='added_date',
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
